import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  MatBadgeModule,
  MatButtonModule,
  MatButtonToggleModule,
  MatCardModule,
  MatDialogModule,
  MatDividerModule,
  MatGridListModule,
  MatIconModule,
  MatInputModule,
  MatMenuModule,
  MatProgressBarModule,
  MatProgressSpinnerModule,
  MatSelectModule,
  MatSidenavModule,
  MatSortModule,
  MatTableModule,
  MatTabsModule,
  MatToolbarModule,
  MatTooltipModule,
  MatExpansionModule,
  MatStepperModule,
  MatListModule, MatRadioModule
} from '@angular/material';
// import { MaterialFileInputModule } from 'ngx-material-file-input';
//

@NgModule({
  imports: [
    CommonModule,
    MatToolbarModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatCardModule,
    MatInputModule,
    MatDialogModule,
    MatTabsModule,
    MatTableModule,
    MatMenuModule,
    MatIconModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatSidenavModule,
    MatTooltipModule,
    MatBadgeModule,
    MatGridListModule,
    MatDividerModule,
    // MaterialFileInputModule,
    MatSortModule,
    MatSelectModule,
    MatExpansionModule,
    MatStepperModule,
    MatListModule,
    MatRadioModule,
  ],
  exports: [
    CommonModule,
    MatToolbarModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatCardModule,
    MatInputModule,
    MatDialogModule,
    MatTabsModule,
    MatTableModule,
    MatMenuModule,
    MatIconModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatSidenavModule,
    MatTooltipModule,
    MatBadgeModule,
    MatGridListModule,
    MatDividerModule,
    // MaterialFileInputModule,
    MatSortModule,
    MatSelectModule,
    MatExpansionModule,
    MatStepperModule,
    MatListModule,
    MatRadioModule,
  ],
})
export class CustomMaterialModule {
}
